- name: "Accessories"
  description: "Accessories"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - cheese
    - font-manager-git
    - galculator
    - gpick
    - flameshot-git
    - liferea
    - mediainfo-gui
    - mcomix
    - nitrogen
    - nomacs
    - nomacs-git
    - nomacs-qt6-git
    - pdfarranger
    - plank
    - arcolinux-plank-themes-git
    - screenkey-git
    - variety
- name: "Conky"
  description: "Conky and conky collection"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - arcolinux-conky-collection-git
    - arcolinux-pipemenus-git
    - conky-lua-archers
    - yad
- name: "Git"
  description: "Git applications"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - gitahead
    - gitg
    - gitfiend
    - github-desktop-bin
    - gitkraken
- name: "Password Manager"
  description: "Password managers"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - bitwarden
    - enpass-bin
    - keepassxc
    - lastpass
- name: "Privacy"
  description: "Applications that ensure your privacy"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - torbrowser-launcher
    - privoxy
- name: "Virtualbox for Linux kernel"
  description: "Installs virtualbox for linux kernel"
  critical: false
  hidden: false
  selected: false
  expanded: false
  packages:
    - virtualbox
    - virtualbox-host-dkms
    - linux
    - linux-headers
- name: "Virtualbox for Linux-lts kernel"
  description: "Installs virtualbox for linux-lts kernel"
  critical: false
  hidden: false
  selected: false
  expanded: false
  packages:
    - virtualbox
    - virtualbox-host-dkms
    - linux-lts
    - linux-lts-headers
- name: "Vmware"
  description: "Installs vmware software"
  critical: false
  hidden: false
  selected: false
  expanded: false
  packages:
    - open-vm-tools
    - vmware-workstation
    - vmware-keymaps
- name: "Qemu software"
  description: "Installs qemu software"
  critical: false
  hidden: false
  selected: false
  expanded: false
  packages:
    - qemu-base
    - qemu-full
    - quickemu
    - quickemu-git
    - quickgui-bin